# Generated by Django 3.1 on 2021-04-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Ficha Técnica',
                'verbose_name_plural': 'Fichas tecnicas',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='datasheet_id',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_ids', to='cart.DataSheet', verbose_name='Atributos'),
        ),
    ]
