# Generated by Django 3.1 on 2021-04-21 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_auto_20210421_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Ficha Técnica',
                'verbose_name_plural': 'Fichas tecnicas',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='brand_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_ids', to='cart.brand', verbose_name='Marca'),
        ),
    ]
