# Generated by Django 3.1 on 2021-05-07 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_auto_20210423_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='datasheet_id',
            field=models.ManyToManyField(blank=True, related_name='product_ids', to='cart.DataSheet', verbose_name='Atributos'),
        ),
    ]
