# Generated by Django 3.1 on 2021-05-22 20:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_auto_20210506_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayuPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionState', models.PositiveIntegerField(choices=[(4, 'Aprobada'), (6, 'Declinada'), (104, 'Error'), (5, 'Expirada'), (7, 'Pendiente'), (None, 'Desconocido')], validators=[django.core.validators.MaxValueValidator(9999)])),
                ('polResponseCode', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999999)])),
                ('polPaymentMethodType', models.PositiveIntegerField(blank=True, choices=[(2, 'CREDIT_CARD'), (4, 'PSE'), (5, 'ACH'), (6, 'DEBIT_CARD'), (7, 'CASH'), (8, 'REFERENCED'), (10, 'BANK_REFERENCED'), (14, 'SPEI'), (None, 'Desconocido')], null=True)),
                ('lapResponseCode', models.CharField(blank=True, max_length=100, null=True)),
                ('lapTransactionState', models.CharField(blank=True, max_length=100, null=True)),
                ('TX_VALUE', models.FloatField(default=0)),
            ],
        ),
    ]
