# Generated by Django 3.1 on 2021-05-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_payupayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payupayment',
            name='reponse_method',
            field=models.CharField(choices=[('confirm', 'Confirmado'), ('response', 'Respuesta'), (None, 'Desconocido')], default='confirm', max_length=25),
        ),
        migrations.AddField(
            model_name='payupayment',
            name='response_message_pol',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
