# Generated by Django 3.1 on 2021-05-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_auto_20210522_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payupayment',
            name='reponse_method',
            field=models.CharField(blank=True, choices=[('confirm', 'Confirmado'), ('response', 'Respuesta'), (None, 'Desconocido')], default='confirm', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='payupayment',
            name='response_message_pol',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
