# Generated by Django 3.1 on 2021-05-27 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0017_auto_20210522_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sended_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='sender_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payupayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='payupayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
