# Generated by Django 3.1 on 2021-06-05 23:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0018_auto_20210527_0140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payupayment',
            old_name='lapResponseCode',
            new_name='lap_response_code',
        ),
        migrations.RenameField(
            model_name='payupayment',
            old_name='lapTransactionState',
            new_name='lap_transaction_state',
        ),
        migrations.RenameField(
            model_name='payupayment',
            old_name='transactionState',
            new_name='payment_method_id',
        ),
        migrations.RenameField(
            model_name='payupayment',
            old_name='polPaymentMethodType',
            new_name='pol_payment_method_type',
        ),
        migrations.RenameField(
            model_name='payupayment',
            old_name='polResponseCode',
            new_name='pol_response_code',
        ),
        migrations.RenameField(
            model_name='payupayment',
            old_name='TX_VALUE',
            new_name='value',
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, default=3, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payu_payment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_id', to='cart.payupayment'),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='payupayment',
            name='lap_payment_method_type',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payupayment',
            name='transaction_state',
            field=models.PositiveIntegerField(blank=True, choices=[(4, 'Aprobada'), (6, 'Declinada'), (104, 'Error'), (5, 'Expirada'), (7, 'Pendiente'), (None, 'Desconocido')], null=True, validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
