# Generated by Django 3.1 on 2021-06-12 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0020_auto_20210612_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='payupayment',
            name='name',
            field=models.CharField(blank=True, default=16, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
