# Generated by Django 3.1 on 2021-06-24 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0022_auto_20210612_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='payupayment',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line_1',
            field=models.CharField(max_length=150, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line_2',
            field=models.CharField(max_length=150, verbose_name='Dirección 2'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(max_length=100, verbose_name='Código postal'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payupayment',
            name='name',
            field=models.CharField(blank=True, default='PAYU-PAYMENT-00202', max_length=255, null=True),
        ),
    ]
