# Generated by Django 3.1 on 2021-06-27 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0024_auto_20210627_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='datasheet_line_ids',
            field=models.ManyToManyField(blank=True, related_name='product_ids', to='cart.DataSheet', verbose_name='Atributos'),
        ),
        migrations.AlterField(
            model_name='datasheet',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datasheet_lines', to='cart.product'),
        ),
        migrations.AlterField(
            model_name='payupayment',
            name='name',
            field=models.CharField(blank=True, default='PAYU-PAYMENT-00226', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_ids', to='cart.brand', verbose_name='Marca'),
        ),
    ]
