# Generated by Django 3.1 on 2021-07-07 16:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0026_auto_20210706_2043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name_plural': 'Imagenes'},
        ),
        migrations.AddField(
            model_name='productimage',
            name='secuence',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='datasheet',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Dato'),
        ),
        migrations.AlterField(
            model_name='datasheet',
            name='value',
            field=models.CharField(max_length=255, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='payupayment',
            name='name',
            field=models.CharField(blank=True, default='PAYU-PAYMENT-00265', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product_images', verbose_name='Imagen'),
        ),
    ]
