# Generated by Django 3.1 on 2021-07-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0027_auto_20210707_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('received', 'Recibido'), ('prepared', 'Preparado'), ('sent', 'Enviado'), ('delivered', 'Entregado')], default='received', max_length=20),
        ),
        migrations.AlterField(
            model_name='payupayment',
            name='name',
            field=models.CharField(blank=True, default='PAYU-PAYMENT-00286', max_length=255, null=True),
        ),
    ]
